# SPDX-License-Identifier: AGPL-3.0-or-later
name: Elixir CI
on: [push, pull_request]

permissions: read-all

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: erlef/setup-beam@e6d7c94229049569db56a7ad5a540c051a010af9 # v1.20.4
        with:
          otp-version: '26'
          elixir-version: '1.16'

      - name: Cache deps
        uses: actions/cache@0c907a75c2c80ebcb7f088228285e798b750cf8f # v4.2.1
        with:
          path: deps
          key: deps-${{ hashFiles('mix.lock') }}

      - name: Install deps
        run: mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Credo lint
        run: mix credo --strict

      - name: Dialyzer
        run: mix dialyzer

      - name: Run tests
        run: mix test --cover

      - name: Security check
        run: mix deps.audit || true
